default_language_version:
    python: python3.12
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: 'https://github.com/PyCQA/flake8'
    rev: 7.0.0
    hooks:
      - id: flake8
  - repo: 'https://github.com/pre-commit/mirrors-isort'
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: 'https://github.com/mgedmin/check-manifest'
    rev: '0.49'
    hooks:
      - id: check-manifest
  - repo: 'https://github.com/myint/autoflake'
    rev: v2.3.0
    hooks:
      - id: autoflake
        args:
          - '--remove-all-unused-imports'
          - '-i'
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
      - id: pyupgrade
        entry: pyupgrade --py3-plus --py36-plus --keep-runtime-typing
