[tool.black]
line-length = 120
target-version = ["py36", "py37", "py38", "py39", "py310", "py311", "py312"]

[tool.isort]
profile = "black"
line_length = 120
known_first_party = ["fluent_compiler"]
default_section= "THIRDPARTY"
skip = [".tox", "dist", "build", ".git"]
